import frappe
from frappe import _
from frappe.utils import flt, nowdate


@frappe.whitelist()
def run_matching_for_requirement(requirement):
	req = frappe.get_doc("Customer Requirement", requirement)
	settings = frappe.get_single("Matching Settings")
	units = _get_candidate_units(req)
	scored = [_score_unit(req, unit, settings) for unit in units]
	scored = [row for row in scored if row["score"] >= flt(settings.minimum_score)]
	scored = sorted(scored, key=lambda row: row["score"], reverse=True)[:10]

	existing = frappe.db.get_value(
		"Match Result",
		{"customer_requirement": req.name, "status": ["!=", "Closed"]},
		"name",
	)
	doc = frappe.get_doc("Match Result", existing) if existing else frappe.new_doc("Match Result")
	doc.customer_requirement = req.name
	doc.match_date = nowdate()
	doc.status = "Open" if scored else "No Suitable Match"
	doc.set("items", [])
	for row in scored:
		doc.append("items", row)
	doc.remarks = _("Generated by Smart Matching from Customer Requirement {0}.").format(req.name)
	doc.save(ignore_permissions=False)

	if scored and req.status in ("New", "Qualified", "Backlog"):
		req.status = "Matched"
		req.save(ignore_permissions=False)

	return doc.name


@frappe.whitelist()
def create_phase_e_validation_data():
	requirements = frappe.get_all(
		"Customer Requirement",
		filters={"preferred_project": "REP-2026-00002"},
		pluck="name",
		limit_page_length=5,
	)
	if not requirements:
		frappe.throw(_("No Customer Requirements found for REP-2026-00002."))
	results = [run_matching_for_requirement(requirement) for requirement in requirements]
	return {"match_results": results}


def _get_candidate_units(req):
	filters = {}
	if req.preferred_project:
		filters["real_estate_project"] = req.preferred_project
	candidates = frappe.get_all(
		"Unit",
		filters=filters,
		fields=[
			"name",
			"status",
			"marketing_status",
			"unit_type",
			"area",
			"expected_sale_price",
			"expected_monthly_rent",
			"real_estate_project",
			"floor",
		],
		limit_page_length=200,
	)
	allowed_statuses = {"Available"}
	return [unit for unit in candidates if (unit.status in allowed_statuses or unit.marketing_status in allowed_statuses)]


def _score_unit(req, unit, settings):
	score = 0
	matched = []
	missed = []

	if req.preferred_project and unit.real_estate_project == req.preferred_project:
		score += flt(settings.location_weight)
		matched.append("Preferred project")
	else:
		missed.append("Preferred project")

	price = flt(unit.expected_monthly_rent if req.requirement_type == "Rent" else unit.expected_sale_price)
	if _between(price, req.budget_min, req.budget_max):
		score += flt(settings.price_weight)
		matched.append("Budget")
	else:
		missed.append("Budget")

	if _between(flt(unit.area), req.preferred_area_min, req.preferred_area_max):
		score += flt(settings.area_weight)
		matched.append("Area")
	else:
		missed.append("Area")

	if req.unit_type and unit.unit_type == req.unit_type:
		score += flt(settings.type_weight)
		matched.append("Unit type")
	elif not req.unit_type:
		score += flt(settings.type_weight) / 2
		matched.append("Flexible unit type")
	else:
		missed.append("Unit type")

	if req.required_features:
		score += flt(settings.feature_weight) / 2
		matched.append("Feature notes reviewed")

	return {
		"unit": unit.name,
		"score": round(score, 2),
		"unit_status": unit.status or unit.marketing_status,
		"unit_type": unit.unit_type,
		"area": flt(unit.area),
		"price_or_rent": price,
		"matched_criteria": ", ".join(matched),
		"missed_criteria": ", ".join(missed),
		"recommendation_notes": _("Review commercial suitability before reservation."),
	}


def _between(value, minimum=None, maximum=None):
	if minimum and value < flt(minimum):
		return False
	if maximum and value > flt(maximum):
		return False
	return True
